### ISSUE TITLE
TypeError: a bytes-like object is required, not 'RangeIndex'

### ISSUE THREAD

**Issue by FireHavvk** [zaccaria-lab/TRACERx_simulation_tool#2]
When I try to execute the example simulation script from the 'make_tx_simulation.ipynb' notebook, I get the following error: 
TypeError: a bytes-like object is required, not 'RangeIndex'

**Comment by abibunkum** [comment]
@FireHavvk Thank you for flagging this. Could you please attach the full error message so that I can try to replicate your issue. Many thanks, Abi.

**Comment by FireHavvk** [comment]
Hi @abibunkum Thank you for your reply. When executing the following command: 

`simulation = make_tx_simulations(n_sims_per_sample_group=1, sample_group_boundaries=None, output_dir=None)`

I get the following error message:

`TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 simulation = make_tx_simulations(n_sims_per_sample_group=1, sample_group_boundaries=None, output_dir=None)

File /mnt/c/Users/Charl/Documents/Cancer_tools/TRACERx_simulation_tool/scripts/./../src/make_simulation.py:47, in make_tx_simulations(n_sims_per_sample_group, sample_group_boundaries, output_dir)
     45 print(patient_name, end=': ')
     46 sim_params = {feature: func(sample_group_df, feature) for feature, func in sample_parameters.items()}
---> 47 output = tx_simulation(patient_name, 
     48             n_nodes = nodes[j],      
     49             n_positions = sim_params['NMutations'],
     50             n_samples = sim_params['NSamples'],
     51             min_clones_per_sample = 3,
     52             max_clones_per_sample = 8,
     53             max_positions=20,
     54             prop_truncal_snvs=sim_params['%MutTruncal'],
     55             prop_pos_gained=sim_params['Gain_Loss'][0],
     56             prop_pos_lost=sim_params['Gain_Loss'][1],    
     57             prop_gained_truncal=sim_params['%GainTruncal'],
     58             prop_lost_truncal=sim_params['%LossTruncal'],
     59             clonal_wgd=sim_params['WGD']['clonal'],
     60             subclonal_wgd=sim_params['WGD']['subclonal'],
     61             n_subclonal_wgd=sim_params['WGD']['subclonal']*1,
     62             minimum_branch_length=1,
     63             constant_multiplicity=True, 
     64             prop_mutloss_positions=mut_loss[j],                  
     65             gain_events=None,
     66             loss_events=None,
     67             mutloss_truncal=mutloss_trunc[j],
     68             all_leaf_observed=True,
     69             coverage=sim_params['Coverage'],
     70             min_tumour_purity=sim_params['Purity'][0],
     71             max_tumour_purity=sim_params['Purity'][1],
     72             fract_noise=noise[j],                               
     73             n_noise_clones=1,                              
     74             noise_type='random',
     75             rs=rs,
     76             display_plots=display_output,
     77             output_directory=output_dir,
     78             ccf_vaf_plots=False,
     79             save_output=save_output,
     80             display_output=True)
     81 if display_output == True:
     82     df_names = ['patient_info_df', 'variant_df', 'clone_df', 'edges_df', 'tx_input_df', 'edge_position_events_df']

File /mnt/c/Users/Charl/Documents/Cancer_tools/TRACERx_simulation_tool/scripts/./../src/simulate.py:77, in tx_simulation(patient_name, n_nodes, n_positions, n_samples, min_clones_per_sample, max_clones_per_sample, max_positions, prop_truncal_snvs, prop_pos_gained, prop_pos_lost, prop_gained_truncal, prop_lost_truncal, clonal_wgd, subclonal_wgd, n_subclonal_wgd, minimum_branch_length, constant_multiplicity, prop_mutloss_positions, gain_events, loss_events, mutloss_truncal, all_leaf_observed, coverage, min_tumour_purity, max_tumour_purity, fract_noise, n_noise_clones, noise_type, rs, display_plots, output_directory, ccf_vaf_plots, save_output, display_output)
     74     noise_clones = None
     75     variant_df['Noise'] = False
---> 77 variant_df, tx_input_df = convert_tree_building_format(variant_df, patient_name) 
     78 edge_position_events_df = variant_df[['VAR_POS', 'CHR', 'POS']].drop_duplicates().merge(edge_position_profiles, on='VAR_POS')
     80 missing_mut = variant_df[['VAR_POS', 'TRUE_CCF']].groupby('VAR_POS')['TRUE_CCF'].sum()

File /mnt/c/Users/Charl/Documents/Cancer_tools/TRACERx_simulation_tool/scripts/./../src/conversion.py:11, in convert_tree_building_format(variant_df, patient_name)
      9 df['PATIENT'] = patient_name
     10 df['SAMPLE'] = df['Sample'].apply(lambda x: 'U_{}_SU_T1.R{}'.format(patient_name, x.split()[1]))
---> 11 df = assign_chr_pos_correct(df, n_pos)
     12 df['REF'], df['ALT'] = np.array([np.tile(np.random.choice(nucleotides, 2, replace=False), n_sample) for i in range(n_pos)]).reshape(-1,2).T
     13 df['REF_COUNT'] = df['Total_Reads'] - df['Variant_Reads']

File /mnt/c/Users/Charl/Documents/Cancer_tools/TRACERx_simulation_tool/scripts/./../src/conversion.py:43, in assign_chr_pos_correct(df, n_positions)
     41 chr_pos_df = pd.DataFrame([chr, pos], index=['CHR', 'POS']).T
     42 assert len(chr_pos_df.drop_duplicates()) == len(chr_pos_df)
---> 43 df = df.merge(chr_pos_df, left_on='Variant_Position', right_on=chr_pos_df.index, how='left')
     44 return df

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/frame.py:10487, in DataFrame.merge(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
  10468 @Substitution("")
  10469 @Appender(_merge_doc, indents=2)
  10470 def merge(
   (...)
  10483     validate: MergeValidate | None = None,
  10484 ) -> DataFrame:
  10485     from pandas.core.reshape.merge import merge
> 10487     return merge(
  10488         self,
  10489         right,
  10490         how=how,
  10491         on=on,
  10492         left_on=left_on,
  10493         right_on=right_on,
  10494         left_index=left_index,
  10495         right_index=right_index,
  10496         sort=sort,
  10497         suffixes=suffixes,
  10498         copy=copy,
  10499         indicator=indicator,
  10500         validate=validate,
  10501     )

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:183, in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
    168 else:
    169     op = _MergeOperation(
    170         left_df,
    171         right_df,
   (...)
    181         validate=validate,
    182     )
--> 183     return op.get_result(copy=copy)

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:883, in _MergeOperation.get_result(self, copy)
    880 if self.indicator:
    881     self.left, self.right = self._indicator_pre_merge(self.left, self.right)
--> 883 join_index, left_indexer, right_indexer = self._get_join_info()
    885 result = self._reindex_and_concat(
    886     join_index, left_indexer, right_indexer, copy=copy
    887 )
    888 result = result.__finalize__(self, method=self._merge_type)

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1133, in _MergeOperation._get_join_info(self)
   1129     join_index, right_indexer, left_indexer = _left_join_on_index(
   1130         right_ax, left_ax, self.right_join_keys, sort=self.sort
   1131     )
   1132 else:
-> 1133     (left_indexer, right_indexer) = self._get_join_indexers()
   1135     if self.right_index:
   1136         if len(self.left) > 0:

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1105, in _MergeOperation._get_join_indexers(self)
   1103 def _get_join_indexers(self) -> tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]]:
   1104     """return the join indexers"""
-> 1105     return get_join_indexers(
   1106         self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how
   1107     )

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1703, in get_join_indexers(left_keys, right_keys, sort, how)
   1698 # get left & right join labels and num. of levels at each location
   1699 mapped = (
   1700     _factorize_keys(left_keys[n], right_keys[n], sort=sort, how=how)
   1701     for n in range(len(left_keys))
   1702 )
-> 1703 zipped = zip(*mapped)
   1704 llab, rlab, shape = (list(x) for x in zipped)
   1706 # get flat i8 keys from label lists

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1700, in <genexpr>(.0)
   1696         return _get_no_sort_one_missing_indexer(left_n, False)
   1698 # get left & right join labels and num. of levels at each location
   1699 mapped = (
-> 1700     _factorize_keys(left_keys[n], right_keys[n], sort=sort, how=how)
   1701     for n in range(len(left_keys))
   1702 )
   1703 zipped = zip(*mapped)
   1704 llab, rlab, shape = (list(x) for x in zipped)

File ~/anaconda3/envs/simulate/lib/python3.9/site-packages/pandas/core/reshape/merge.py:2500, in _factorize_keys(lk, rk, sort, how)
   2495 else:
   2496     # Argument 1 to "factorize" of "ObjectFactorizer" has incompatible type
   2497     # "Union[ndarray[Any, dtype[signedinteger[_64Bit]]],
   2498     # ndarray[Any, dtype[object_]]]"; expected "ndarray[Any, dtype[object_]]"
   2499     llab = rizer.factorize(lk)  # type: ignore[arg-type]
-> 2500     rlab = rizer.factorize(rk)  # type: ignore[arg-type]
   2501 assert llab.dtype == np.dtype(np.intp), llab.dtype
   2502 assert rlab.dtype == np.dtype(np.intp), rlab.dtype

File pandas/_libs/hashtable_class_helper.pxi:3045, in pandas._libs.hashtable.Int64Factorizer.factorize()

File stringsource:660, in View.MemoryView.memoryview_cwrapper()

File stringsource:350, in View.MemoryView.memoryview.__cinit__()

TypeError: a bytes-like object is required, not 'RangeIndex'`

**Comment by abibunkum** [comment]
Hi @FireHavvk - Thank you so much for sending this. Unfortunately I cannot replicate your error, however I have implemented some changes where the error was being caused that may hopefully fix the problem. Could you please try pulling the updates and testing to see if this fixes the issue? Thank you so much.

**Comment by FireHavvk** [comment]
Hi @abibunkum, That seems to have fixed the issue. Thank you so much!
